---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aftazaco/public_html/aftaza
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm install
    - npx prisma generate
    - export NODE_OPTIONS="--max-old-space-size=1024"
    - npm run build
