---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aftazaco/public_html/aftaza
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - /bin/cp .env.example .env 2>/dev/null || true
    - npm install --production
    - export NODE_OPTIONS="--max-old-space-size=1024"
    - npm run build
